WebSeed.create url: "http://www.outitude.com"
WebSeed.create url: "http://www.google.com"
WebSeed.create url: "http://www.rupeal.com"
WebSeed.create url: "http://www.weareswat.com"
WebSeed.create url: "http://www.apple.com"
WebSeed.create url: "http://www.hackernews.com"
